- platform: rest
  name: "GasBuddy Stations Nearby Info"
  icon: mdi:gas-station
  scan_interval: 3600
  resource: https://www.gasbuddy.com/graphql
  method: POST
  headers:
    Content-Type: application/json
  payload: >
    {
      "operationName": "LocationBySearchTerm",
      "variables": {
          "maxAge": 0,
          "search": "YOURPOSTALCODE"
      },
      "query": "query LocationBySearchTerm($brandId: Int, $cursor: String, $maxAge: Int, $search: String) { locationBySearchTerm(search: $search) { stations(brandId: $brandId, cursor: $cursor, maxAge: $maxAge) { count cursor { next } results {  address { country line1 line2 locality postalCode region }  fuels id name prices { cash { nickname postedTime price } credit { nickname postedTime price } } } } trends { areaName country today todayLow trend } } }"
    }
  state_class: measurement
  value_template: "{{ range(1, 10240) | random }}"
    #The point of this sensor is its attributes. Using a random dummy value
  json_attributes_path: "$.data.locationBySearchTerm"
  json_attributes:
    - stations
    - trends
